"""Initial database setup

Revision ID: e1e5de830cb9
Revises: 
Create Date: 2025-08-14 09:24:24.245243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e5de830cb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('logger_name', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pt_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addedon', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('site', sa.String(length=32), nullable=True),
    sa.Column('auto_update', sa.Boolean(), nullable=True),
    sa.Column('update_interval', sa.Integer(), nullable=True),
    sa.Column('updateing', sa.Integer(), nullable=True),
    sa.Column('icopath', sa.String(length=256), nullable=True),
    sa.Column('cookie', sa.String(length=1024), nullable=True),
    sa.Column('siteNewLink', sa.String(length=256), nullable=True),
    sa.Column('siteNewCheck', sa.Boolean(), nullable=True),
    sa.Column('lastSearchCheck', sa.Boolean(), nullable=True),
    sa.Column('lastResultCount', sa.Integer(), nullable=True),
    sa.Column('newTorCount', sa.Integer(), nullable=True),
    sa.Column('lastNewStatus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qbit_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qbitname', sa.String(length=50), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('docker_from', sa.String(length=200), nullable=True),
    sa.Column('docker_to', sa.String(length=200), nullable=True),
    sa.Column('link_dir', sa.String(length=200), nullable=True),
    sa.Column('auto_delete', sa.Boolean(), nullable=True),
    sa.Column('islocal', sa.Boolean(), nullable=True),
    sa.Column('run_torcp_by_api', sa.Boolean(), nullable=True),
    sa.Column('disk_free_margin', sa.Integer(), nullable=True),
    sa.Column('add_pause', sa.Boolean(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('after_dl_prog', sa.String(length=200), nullable=True),
    sa.Column('mroot_mount', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_torrent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addedon', sa.DateTime(), nullable=True),
    sa.Column('site', sa.String(length=32), nullable=True),
    sa.Column('tortitle', sa.String(length=256), nullable=True),
    sa.Column('infolink', sa.String(length=256), nullable=True),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('downlink', sa.String(length=256), nullable=True),
    sa.Column('mediatype', sa.String(length=32), nullable=True),
    sa.Column('mediasource', sa.String(length=32), nullable=True),
    sa.Column('tmdbtitle', sa.String(length=256), nullable=True),
    sa.Column('tmdbcat', sa.String(length=32), nullable=True),
    sa.Column('tmdbid', sa.Integer(), nullable=True),
    sa.Column('tmdbyear', sa.Integer(), nullable=True),
    sa.Column('tmdbposter', sa.String(length=64), nullable=True),
    sa.Column('genrestr', sa.String(length=128), nullable=True),
    sa.Column('tmdboverview', sa.Text(), nullable=True),
    sa.Column('tagspecial', sa.String(length=32), nullable=True),
    sa.Column('taggy', sa.Boolean(), nullable=True),
    sa.Column('tagzz', sa.Boolean(), nullable=True),
    sa.Column('tagfree', sa.Boolean(), nullable=True),
    sa.Column('tag2xfree', sa.Boolean(), nullable=True),
    sa.Column('tag50off', sa.Boolean(), nullable=True),
    sa.Column('imdbstr', sa.String(length=16), nullable=True),
    sa.Column('imdbval', sa.Float(), nullable=True),
    sa.Column('doubanval', sa.Float(), nullable=True),
    sa.Column('doubanid', sa.String(length=16), nullable=True),
    sa.Column('seednum', sa.Integer(), nullable=True),
    sa.Column('downnum', sa.Integer(), nullable=True),
    sa.Column('torsizestr', sa.String(length=16), nullable=True),
    sa.Column('torsizeint', sa.BigInteger(), nullable=True),
    sa.Column('tordate', sa.DateTime(), nullable=True),
    sa.Column('dlcount', sa.Integer(), nullable=True),
    sa.Column('videocodec', sa.String(length=16), nullable=True),
    sa.Column('audiocodec', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tor_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_title', sa.String(length=255), nullable=True),
    sa.Column('extitle', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('title_translation', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('year_int', sa.Integer(), nullable=True),
    sa.Column('tmdbtype', sa.String(length=20), nullable=True),
    sa.Column('tmdbid', sa.String(length=20), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('episode', sa.String(length=20), nullable=True),
    sa.Column('epnum', sa.String(length=20), nullable=True),
    sa.Column('fullseason', sa.Boolean(), nullable=True),
    sa.Column('imdbstr', sa.String(length=20), nullable=True),
    sa.Column('doubanid', sa.String(length=20), nullable=True),
    sa.Column('imdbval', sa.Float(), nullable=True),
    sa.Column('doubanval', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('mediasource', sa.String(length=20), nullable=True),
    sa.Column('audiocodec', sa.String(length=20), nullable=True),
    sa.Column('videocodec', sa.String(length=20), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('sizestr', sa.String(length=20), nullable=True),
    sa.Column('seednum', sa.Integer(), nullable=True),
    sa.Column('downnum', sa.Integer(), nullable=True),
    sa.Column('pubdate', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tor_details_doubanid'), 'tor_details', ['doubanid'], unique=False)
    op.create_index(op.f('ix_tor_details_extitle'), 'tor_details', ['extitle'], unique=False)
    op.create_index(op.f('ix_tor_details_group'), 'tor_details', ['group'], unique=False)
    op.create_index(op.f('ix_tor_details_imdbstr'), 'tor_details', ['imdbstr'], unique=False)
    op.create_index(op.f('ix_tor_details_media_title'), 'tor_details', ['media_title'], unique=False)
    op.create_index(op.f('ix_tor_details_tmdbid'), 'tor_details', ['tmdbid'], unique=False)
    op.create_index(op.f('ix_tor_details_tmdbtype'), 'tor_details', ['tmdbtype'], unique=False)
    op.create_table('torrent_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addedon', sa.DateTime(), nullable=True),
    sa.Column('site', sa.String(length=32), nullable=True),
    sa.Column('searchword', sa.String(length=64), nullable=True),
    sa.Column('tortitle', sa.String(length=256), nullable=True),
    sa.Column('infolink', sa.String(length=256), nullable=True),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('downlink', sa.String(length=256), nullable=True),
    sa.Column('mediatype', sa.String(length=32), nullable=True),
    sa.Column('mediasource', sa.String(length=32), nullable=True),
    sa.Column('tmdbtitle', sa.String(length=256), nullable=True),
    sa.Column('tmdbcat', sa.String(length=16), nullable=True),
    sa.Column('tmdbid', sa.Integer(), nullable=True),
    sa.Column('tmdbyear', sa.Integer(), nullable=True),
    sa.Column('tmdbposter', sa.String(length=64), nullable=True),
    sa.Column('genrestr', sa.String(length=128), nullable=True),
    sa.Column('tmdboverview', sa.Text(), nullable=True),
    sa.Column('tagspecial', sa.String(length=32), nullable=True),
    sa.Column('taggy', sa.Boolean(), nullable=True),
    sa.Column('tagzz', sa.Boolean(), nullable=True),
    sa.Column('tagfree', sa.Boolean(), nullable=True),
    sa.Column('tag2xfree', sa.Boolean(), nullable=True),
    sa.Column('tag50off', sa.Boolean(), nullable=True),
    sa.Column('imdbstr', sa.String(length=16), nullable=True),
    sa.Column('imdbval', sa.Float(), nullable=True),
    sa.Column('doubanval', sa.Float(), nullable=True),
    sa.Column('doubanid', sa.String(length=16), nullable=True),
    sa.Column('seednum', sa.Integer(), nullable=True),
    sa.Column('downnum', sa.Integer(), nullable=True),
    sa.Column('torsizestr', sa.String(length=16), nullable=True),
    sa.Column('torsizeint', sa.BigInteger(), nullable=True),
    sa.Column('tordate', sa.DateTime(), nullable=True),
    sa.Column('dlcount', sa.Integer(), nullable=True),
    sa.Column('videocodec', sa.String(length=16), nullable=True),
    sa.Column('audiocodec', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=False),
    sa.Column('tor_detail_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('info_link', sa.String(length=255), nullable=True),
    sa.Column('download_link', sa.String(length=255), nullable=True),
    sa.Column('accept', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'IGNORED', 'ERROR', 'OPTPICK', 'DUPE', name='acceptstatus'), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.Column('rssname', sa.String(length=64), nullable=True),
    sa.Column('rsstags', sa.String(length=64), nullable=True),
    sa.Column('pubdate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tor_detail_id'], ['tor_details.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rss_history_site'), 'rss_history', ['site'], unique=False)
    op.create_table('tor_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addedon', sa.DateTime(), nullable=True),
    sa.Column('src', sa.String(length=16), nullable=True),
    sa.Column('tor_detail_id', sa.Integer(), nullable=True),
    sa.Column('qbitname', sa.String(length=50), nullable=True),
    sa.Column('qbid', sa.String(length=128), nullable=True),
    sa.Column('torname', sa.String(length=256), nullable=True),
    sa.Column('site', sa.String(length=32), nullable=True),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('torimdb', sa.String(length=20), nullable=True),
    sa.Column('infolink', sa.String(length=256), nullable=True),
    sa.Column('downloadlink', sa.String(length=256), nullable=True),
    sa.Column('taglist', sa.String(length=256), nullable=True),
    sa.Column('auto_cat', sa.String(length=64), nullable=True),
    sa.Column('torcped', sa.Boolean(), nullable=True),
    sa.Column('torcped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tor_detail_id'], ['tor_details.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tor_download_qbid'), 'tor_download', ['qbid'], unique=False)
    op.create_index(op.f('ix_tor_download_qbitname'), 'tor_download', ['qbitname'], unique=False)
    op.create_table('tor_media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addedon', sa.DateTime(), nullable=True),
    sa.Column('torname', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('torsite', sa.String(length=64), nullable=True),
    sa.Column('torsitecat', sa.String(length=20), nullable=True),
    sa.Column('torimdb', sa.String(length=20), nullable=True),
    sa.Column('torhash', sa.String(length=120), nullable=True),
    sa.Column('torsize', sa.BigInteger(), nullable=True),
    sa.Column('tmdbid', sa.Integer(), nullable=True),
    sa.Column('tmdbcat', sa.String(length=20), nullable=True),
    sa.Column('tmdbposter', sa.String(length=120), nullable=True),
    sa.Column('tmdbyear', sa.Integer(), nullable=True),
    sa.Column('tmdbgenreids', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('plexid', sa.String(length=120), nullable=True),
    sa.Column('season', sa.String(length=128), nullable=True),
    sa.Column('episode', sa.String(length=128), nullable=True),
    sa.Column('fullseason', sa.Boolean(), nullable=True),
    sa.Column('mediasource', sa.String(length=32), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('tordownload_qbid', sa.String(length=64), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.Column('medianame', sa.String(length=256), nullable=True),
    sa.Column('infolink', sa.String(length=256), nullable=True),
    sa.Column('qbitname', sa.String(length=64), nullable=True),
    sa.Column('tor_detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tor_detail_id'], ['tor_details.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tor_media_items_medianame'), 'tor_media_items', ['medianame'], unique=False)
    op.create_index(op.f('ix_tor_media_items_title'), 'tor_media_items', ['title'], unique=False)
    op.create_index(op.f('ix_tor_media_items_torimdb'), 'tor_media_items', ['torimdb'], unique=False)
    op.create_index(op.f('ix_tor_media_items_torname'), 'tor_media_items', ['torname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tor_media_items_torname'), table_name='tor_media_items')
    op.drop_index(op.f('ix_tor_media_items_torimdb'), table_name='tor_media_items')
    op.drop_index(op.f('ix_tor_media_items_title'), table_name='tor_media_items')
    op.drop_index(op.f('ix_tor_media_items_medianame'), table_name='tor_media_items')
    op.drop_table('tor_media_items')
    op.drop_index(op.f('ix_tor_download_qbitname'), table_name='tor_download')
    op.drop_index(op.f('ix_tor_download_qbid'), table_name='tor_download')
    op.drop_table('tor_download')
    op.drop_index(op.f('ix_rss_history_site'), table_name='rss_history')
    op.drop_table('rss_history')
    op.drop_table('torrent_cache')
    op.drop_index(op.f('ix_tor_details_tmdbtype'), table_name='tor_details')
    op.drop_index(op.f('ix_tor_details_tmdbid'), table_name='tor_details')
    op.drop_index(op.f('ix_tor_details_media_title'), table_name='tor_details')
    op.drop_index(op.f('ix_tor_details_imdbstr'), table_name='tor_details')
    op.drop_index(op.f('ix_tor_details_group'), table_name='tor_details')
    op.drop_index(op.f('ix_tor_details_extitle'), table_name='tor_details')
    op.drop_index(op.f('ix_tor_details_doubanid'), table_name='tor_details')
    op.drop_table('tor_details')
    op.drop_table('site_torrent')
    op.drop_table('qbit_config')
    op.drop_table('pt_site')
    op.drop_table('logs')
    # ### end Alembic commands ###
