"""Create rss_feed_configs table

Revision ID: e230cb4159fc
Revises: e1e5de830cb9
Create Date: 2025-08-14 14:04:59.151127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e230cb4159fc'
down_revision: Union[str, Sequence[str], None] = 'e1e5de830cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feed_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('rssUrl', sa.String(length=512), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=False),
    sa.Column('qbCategory', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('getDetail', sa.Boolean(), nullable=True),
    sa.Column('optpick', sa.String(length=255), nullable=True),
    sa.Column('qbitname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rss_feed_configs_id'), 'rss_feed_configs', ['id'], unique=False)
    op.create_index(op.f('ix_rss_feed_configs_name'), 'rss_feed_configs', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rss_feed_configs_name'), table_name='rss_feed_configs')
    op.drop_index(op.f('ix_rss_feed_configs_id'), table_name='rss_feed_configs')
    op.drop_table('rss_feed_configs')
    # ### end Alembic commands ###
